on:
  push:
    branches:
      - 'master'
      - 'main'
      - 'release/*'
  pull_request:
    branches:
      - 'master'
      - 'main'
      - 'release/*'

name: CI

jobs:

  build_test:
    name: Build and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - version: stable
          - version: 1.88.0 # MSRV
            msrv: true
        features:
          - --no-default-features
          - --features default
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust.version }}
          override: true
          profile: minimal
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.2.1
      - name: Install libusb
        run: sudo apt install libusb-1.0-0-dev
      - name: Use MSRV Cargo.toml # Don't include "cli" in workspace if using MSRV
        if: ${{ matrix.rust.msrv }}
        run: cp Cargo.toml.MSRV Cargo.toml
      - name: Build
        run: cargo build ${{ matrix.features }}
      - name: Test
        run: cargo test ${{ matrix.features }}

  build_static_musl:
    name: Build static musl binary
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Install Nix
        uses: cachix/install-nix-action@v22
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build static binary
        run: |
          nix develop -c cargo build --release --target x86_64-unknown-linux-musl
          # Verify it's actually static
          ldd target/x86_64-unknown-linux-musl/release/cktap-direct 2>&1 | grep -q "statically linked"

  rust_fmt:
    name: Rust fmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
          components: rustfmt
      - name: Check fmt
        run: cargo fmt --all -- --config format_code_in_doc_comments=true --check

  clippy_check:
    name: Clippy check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
          override: true
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.2.1
      - name: Install libusb
        run: sudo apt install libusb-1.0-0-dev
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features --all-targets -- -D warnings

